icgc-argo/dac-ui

components/DefaultPageLayout.tsx
components/PageHeader.tsx
components/pages/Applications/ApplicationForm/Forms/index.tsx
components/pages/Applications/ApplicationForm/Header/Actions.tsx
components/pages/Applications/ApplicationForm/Header/Details.tsx
components/pages/Applications/ApplicationForm/Header/Progress.tsx
components/pages/Applications/ApplicationForm/Header/index.tsx
components/pages/Applications/ApplicationForm/index.tsx
components/pages/Applications/index.tsx
package-lock.json
package.json
pages/applications/[[...ID]].tsx

Creates the template for this:
in order to see it use `/applications/1234` or whatever fake ID you want to try.

14 - add application page with basic titlebar

---

components/Head.tsx
components/NavBar.tsx

Minor fixes that were missed in initial pr for #2

💄 Remove contact from header, fix favicon

---

components/DefaultPageLayout.tsx
components/Head.tsx
components/NavBar.tsx
components/pages/Applications/ApplicationForm/Forms/Outline/Section.tsx
components/pages/Applications/ApplicationForm/Forms/Outline/ValidationIcon.tsx
components/pages/Applications/ApplicationForm/Forms/Outline/constants.ts
components/pages/Applications/ApplicationForm/Forms/Outline/helpers.ts
components/pages/Applications/ApplicationForm/Forms/Outline/index.tsx
components/pages/Applications/ApplicationForm/Forms/constants.ts
components/pages/Applications/ApplicationForm/Forms/index.tsx
components/pages/Applications/ApplicationForm/Forms/types.ts
components/pages/Applications/ApplicationForm/Forms/useFormValidation.ts
components/pages/Applications/ApplicationForm/Header/Actions.tsx
components/pages/Applications/ApplicationForm/Header/Details.tsx
components/pages/Applications/ApplicationForm/Header/Progress.tsx
components/pages/Applications/ApplicationForm/Header/index.tsx
components/pages/Applications/ApplicationForm/index.tsx
package-lock.json
package.json

bonus:
- fix favicon path being relative to pages
- fix Navbar's shadow being covered by content elements

15 - add interactions and styling to application outline tabs

---

components/DefaultPageLayout.tsx
components/Head.tsx
components/NavBar.tsx
components/pages/Applications/ApplicationForm/Forms/Outline/Section.tsx
components/pages/Applications/ApplicationForm/Forms/Outline/ValidationIcon.tsx
components/pages/Applications/ApplicationForm/Forms/Outline/constants.ts
components/pages/Applications/ApplicationForm/Forms/Outline/helpers.ts
components/pages/Applications/ApplicationForm/Forms/Outline/index.tsx
components/pages/Applications/ApplicationForm/Forms/constants.ts
components/pages/Applications/ApplicationForm/Forms/index.tsx
components/pages/Applications/ApplicationForm/Forms/types.ts
components/pages/Applications/ApplicationForm/Forms/useFormValidation.ts
components/pages/Applications/ApplicationForm/Header/Actions.tsx
components/pages/Applications/ApplicationForm/Header/Details.tsx
components/pages/Applications/ApplicationForm/Header/Progress.tsx
components/pages/Applications/ApplicationForm/Header/index.tsx
components/pages/Applications/ApplicationForm/index.tsx
package-lock.json
package.json

🔖 rc 0.2.1

---

components/pages/Applications/ApplicationForm/Header/Actions.tsx

Just changing the label of the button, plus linting noise.

change download pdf button label

---

components/pages/Applications/ApplicationForm/Forms/Representative.tsx
components/pages/Applications/ApplicationForm/Forms/constants.tsx
components/pages/Applications/ApplicationForm/Forms/types.ts
components/pages/Applications/ApplicationForm/Forms/validations/schemas.ts

Now this one is literally just adding new stuff. Pretty much copy paste of the applicant info section, since no new functionality is added.

18 - add institutional representative section to application forms

---

.babelrc
components/pages/Applications/ApplicationForm/Forms/validations/schemas.ts

These validations were a bit too strict.

address feedback on form sections

---

components/pages/Applications/ApplicationForm/Forms/EthicsLetter.tsx
components/pages/Applications/ApplicationForm/Forms/constants.tsx
components/pages/Applications/ApplicationForm/Forms/index.tsx
components/pages/Applications/ApplicationForm/Forms/types.ts
package-lock.json
package.json

As per discussion with @rosibaj and @blabadi, we're adding only the base layout for this section, without interactive validation; so we can move forward with an MVP sooner.
The rest of the functionality will be added later, along with the corresponding ticket (#22)

22 - add Ethics section base layout to application forms

---

components/pages/Applications/ApplicationForm/Forms/DoubleFieldRow.tsx
components/pages/Applications/ApplicationForm/Forms/FormFieldHelpBubble.tsx
components/pages/Applications/ApplicationForm/Forms/ProjectInfo/PublicationURLs.tsx
components/pages/Applications/ApplicationForm/Forms/ProjectInfo/index.tsx
components/pages/Applications/ApplicationForm/Forms/constants.tsx
components/pages/Applications/ApplicationForm/Forms/index.tsx
components/pages/Applications/ApplicationForm/Forms/types.ts
components/pages/Applications/ApplicationForm/Forms/validations/helpers.ts
components/pages/Applications/ApplicationForm/Forms/validations/index.ts
components/pages/Applications/ApplicationForm/Forms/validations/schemas.ts

This code includes the layout and validation for the input and textarea fields, but doesn't include the full validation + interaction logic for the Publication URLs, which will be added in a separate ticket

21 - add project information section to application forms

---

components/pages/Applications/ApplicationForm/Forms/DataAccessAgreements.tsx
components/pages/Applications/ApplicationForm/Forms/ITAgreements.tsx

As per https://github.com/icgc-argo/dac-ui/issues/23#issuecomment-862670899

realign list item markers

---

components/pages/Applications/ApplicationForm/Forms/Appendices.tsx
components/pages/Applications/ApplicationForm/Forms/DoubleFieldRow.tsx
components/pages/Applications/ApplicationForm/Forms/FormFieldHelpBubble.tsx
components/pages/Applications/ApplicationForm/Forms/ProjectInfo/PublicationURLs.tsx
components/pages/Applications/ApplicationForm/Forms/Representative.tsx
components/pages/Applications/ApplicationForm/Forms/validations/schemas.ts
components/pages/Applications/Dashboard/Applications/InProgress/ButtonGroup.tsx

Changes requested in tickets #21 and #25

make feedback changes for Project info and Appendices Application form

---

components/DefaultPageLayout.tsx
components/Root.tsx
components/pages/Applications/index.tsx
global/constants/externalPaths.ts
global/constants/index.ts
global/hooks/useApplicationsAPI.tsx
global/hooks/useAuthContext.tsx
pages/_app.tsx
pages/logged-in.tsx

Initial commit to reduce the size of my upcoming PR for #51, attempting to reduce/split complexity for the reviewing Dev Ninjas ⚔️

51 - improve the initial loads when logging in

---

components/pages/Applications/ApplicationForm/Forms/Collaborators.tsx
components/pages/Applications/ApplicationForm/Header/Details.tsx
components/pages/Applications/ApplicationForm/Header/index.tsx
components/pages/Applications/ApplicationForm/index.tsx
components/pages/Applications/index.tsx
global/hooks/useApplicationsAPI.tsx
global/hooks/useAuthContext.tsx

Makes the application header come to life ⚡

51 - feed metadata into application header

---

components/ApplicationProgressBar/types.ts
components/pages/Applications/ApplicationForm/Forms/Appendices.tsx
components/pages/Applications/ApplicationForm/Forms/Applicant.tsx
components/pages/Applications/ApplicationForm/Forms/DataAccessAgreement.tsx
components/pages/Applications/ApplicationForm/Forms/EthicsLetter.tsx
components/pages/Applications/ApplicationForm/Forms/ITAgreements.tsx
components/pages/Applications/ApplicationForm/Forms/Introduction.tsx
components/pages/Applications/ApplicationForm/Forms/Outline/index.tsx
components/pages/Applications/ApplicationForm/Forms/ProjectInfo/PublicationURLs.tsx
components/pages/Applications/ApplicationForm/Forms/ProjectInfo/index.tsx
components/pages/Applications/ApplicationForm/Forms/Representative.tsx
components/pages/Applications/ApplicationForm/Forms/constants.tsx
components/pages/Applications/ApplicationForm/Forms/helpers.tsx
components/pages/Applications/ApplicationForm/Forms/index.tsx
components/pages/Applications/ApplicationForm/Forms/types.ts
components/pages/Applications/ApplicationForm/Forms/validations/helpers.ts
components/pages/Applications/ApplicationForm/Forms/validations/index.ts
components/pages/Applications/ApplicationForm/Forms/validations/schemas.ts
components/pages/Applications/ApplicationForm/Header/Progress.tsx
components/pages/Applications/ApplicationForm/Header/index.tsx
components/pages/Applications/index.tsx
components/pages/Applications/types.ts
package-lock.json

- fills the fields with persisted data
- disables them when the section is disabled
- updates the sections' statuses accordingly
does not (pending new ticket numbers):
- save data
- display error messages

49 - load Application form data

---

components/ApplicationProgressBar/types.ts
components/pages/Applications/ApplicationForm/Forms/Appendices.tsx
components/pages/Applications/ApplicationForm/Forms/Applicant.tsx
components/pages/Applications/ApplicationForm/Forms/DataAccessAgreement.tsx
components/pages/Applications/ApplicationForm/Forms/EthicsLetter.tsx
components/pages/Applications/ApplicationForm/Forms/ITAgreements.tsx
components/pages/Applications/ApplicationForm/Forms/Introduction.tsx
components/pages/Applications/ApplicationForm/Forms/Outline/index.tsx
components/pages/Applications/ApplicationForm/Forms/ProjectInfo/PublicationURLs.tsx
components/pages/Applications/ApplicationForm/Forms/ProjectInfo/index.tsx
components/pages/Applications/ApplicationForm/Forms/Representative.tsx
components/pages/Applications/ApplicationForm/Forms/constants.tsx
components/pages/Applications/ApplicationForm/Forms/helpers.tsx
components/pages/Applications/ApplicationForm/Forms/index.tsx
components/pages/Applications/ApplicationForm/Forms/types.ts
components/pages/Applications/ApplicationForm/Forms/validations/helpers.ts
components/pages/Applications/ApplicationForm/Forms/validations/index.ts
components/pages/Applications/ApplicationForm/Forms/validations/schemas.ts
components/pages/Applications/ApplicationForm/Header/Progress.tsx
components/pages/Applications/ApplicationForm/Header/index.tsx
components/pages/Applications/index.tsx
components/pages/Applications/types.ts
package-lock.json
package.json

#49 Load Application Data + Sidebar States for each section/state of application

🔖 rc 0.10.0

---

components/pages/Applications/ApplicationForm/Forms/Applicant.tsx
components/pages/Applications/ApplicationForm/Forms/Representative.tsx
components/pages/Applications/ApplicationForm/Forms/types.ts
components/pages/Applications/ApplicationForm/Forms/validations/schemas.ts
components/pages/Applications/index.tsx

168 - field name corrections

---

components/pages/Applications/ApplicationForm/Forms/Applicant.tsx
components/pages/Applications/ApplicationForm/Forms/Collaborators.tsx
components/pages/Applications/ApplicationForm/Forms/Representative.tsx
components/pages/Applications/ApplicationForm/Forms/types.ts
components/pages/Applications/ApplicationForm/Forms/validations/schemas.ts
components/pages/Applications/index.tsx
package-lock.json
package.json

#20 - adds the `Collaborator` modal
#168 - corrects some field names to match the BE

🔖 rc 0.10.1

---

components/pages/Applications/ManageApplications/utils.tsx

show 50 applications per page by default

#147: set rows to 50

---

components/pages/Applications/ApplicationForm/Forms/validations/helpers.ts
components/pages/Applications/ApplicationForm/Forms/validations/schemas.ts

An error is coming up as a result of mistakenly enabling the Ethics Letter validation, while a validation schema hadn't been added.

203 - add missing EthicsLetter schema to avoid error message

---

components/ApplicationProgressBar/index.tsx
components/pages/Applications/ApplicationForm/Forms/Collaborators.tsx
components/pages/Applications/ApplicationForm/Forms/Signature.tsx
components/pages/Applications/ApplicationForm/Forms/constants.tsx
components/pages/Applications/ApplicationForm/Forms/helpers.tsx
components/pages/Applications/ApplicationForm/Forms/index.tsx
components/pages/Applications/ApplicationForm/Forms/types.ts
components/pages/Applications/Dashboard/Applications/InProgress/ButtonGroup.tsx
components/pages/Applications/Dashboard/Applications/InProgress/constants.ts
components/pages/Applications/Dashboard/Applications/InProgress/helpers.ts
components/pages/Applications/Dashboard/Applications/InProgress/index.tsx
package.json

https://github.com/icgc-argo/dac-ui/issues/26 - applicant sign and submit section
https://github.com/icgc-argo/dac-ui/issues/174 - collab modal feedback
https://github.com/icgc-argo/dac-ui/issues/122 - dashboard progress bar feedback

🔖 rc 0.15.0

---

components/pages/Applications/ApplicationForm/Forms/EthicsLetter.tsx
components/pages/Applications/ApplicationForm/Forms/EthicsLetter/NoFilesMessage.tsx
components/pages/Applications/ApplicationForm/Forms/EthicsLetter/UploadsTable.tsx
components/pages/Applications/ApplicationForm/Forms/EthicsLetter/index.tsx
components/pages/Applications/ApplicationForm/Forms/FormFieldHelpBubble.tsx
components/pages/Applications/ApplicationForm/Forms/Outline/index.tsx
components/pages/Applications/ApplicationForm/Forms/Signature.tsx
components/pages/Applications/ApplicationForm/Forms/Terms.tsx
components/pages/Applications/ApplicationForm/Forms/helpers.tsx
components/pages/Applications/ApplicationForm/Forms/types.ts
components/pages/Applications/ApplicationForm/Forms/validations/helpers.ts
components/pages/Applications/ApplicationForm/Forms/validations/index.ts
components/pages/Applications/ApplicationForm/Forms/validations/schemas.ts
package-lock.json
package.json

Completes the functionality for Ethics Letter

#141 - ethics v2

---

components/pages/Applications/ApplicationForm/RequestRevisionsBar/RequestRevisionsModal.tsx
components/pages/Applications/ApplicationForm/RequestRevisionsBar/index.tsx

- enable reviewers submitting revisions (copied this from the approval modal)
- hide admin buttons in revisions requested state

#62: submit request revisions

---

components/pages/Applications/ApplicationForm/Forms/Collaborators.tsx
components/pages/Applications/Dashboard/Applications/InProgress/ButtonGroup.tsx
components/pages/Applications/Dashboard/Applications/InProgress/helpers.ts
components/pages/Applications/Dashboard/Applications/InProgress/index.tsx
components/pages/Applications/Dashboard/Applications/index.tsx
components/pages/Applications/Dashboard/Card.tsx
components/pages/Applications/Dashboard/index.tsx
components/pages/Applications/index.tsx
components/pages/Applications/types.ts

- load in card data for user applications
- update cards
- use correct dates for submission, approval, etc if available
- enable links
- made the cards a bit wider
- styling fixes

#215: data hookup - applicant dashboard

---

components/ApplyForAccessModal.tsx
components/NavBar.tsx
components/Root.tsx
components/pages/Home/index.tsx
global/constants/externalPaths.ts

- move ego link to constants
- add apply for access modal that opens from the homepage & the header

#7: apply for access modal 

---

components/pages/Applications/Dashboard/Applications/InProgress/constants.ts

#215 - fix date formatting on app card

---

components/pages/Applications/ApplicationForm/Forms/common.tsx
components/pages/Applications/ApplicationForm/Header/Actions.tsx

Restores pdf button loading state reset in generate function.

🐛 255 - fix pdf loading state

---

components/pages/Applications/ApplicationForm/Forms/common.tsx
components/pages/Applications/ApplicationForm/Header/Actions.tsx

Use same state update as in Signature component.
Type data in generatePDF func

🎨 255 - Improve pdf loading state fix

---

components/pages/Applications/ApplicationForm/Forms/index.tsx
components/pages/Applications/ApplicationForm/Forms/types.ts
components/pages/Applications/ApplicationForm/Forms/validations/index.ts

Displays error messages for each field indicated in the sections `errorList` provided by the API payload.

163 - show validation errors based on BE errorList fields

---

components/pages/Applications/ApplicationForm/Header/Actions.tsx

comment out Close Application button
this user flow won't be implemented in time for soft launch

comment out Close Application button.

---

components/NavBar.tsx
components/pages/Applications/ApplicationForm/Forms/index.tsx
components/pages/Applications/ApplicationForm/Forms/types.ts
components/pages/Applications/ApplicationForm/Forms/validations/index.ts
components/pages/Applications/ApplicationForm/Header/Actions.tsx
package-lock.json
package.json

Includes tickets:
#39
#163
#250

🔖 rc 0.19.1

---

components/pages/Applications/ApplicationForm/Forms/validations/index.ts

Note: As a reassessment of #163, we won't validate values following the API's `errorsList` array, but all fields that contain a value.

280 - reduce validation aggro and load persisted failed values

---

components/pages/Applications/ApplicationForm/Forms/Outline/Section.tsx
components/pages/Applications/ApplicationForm/Forms/Outline/helpers.ts
components/pages/Applications/ApplicationForm/Forms/constants.tsx
components/pages/Applications/ApplicationForm/Forms/helpers.tsx
components/pages/Applications/ApplicationForm/Forms/types.ts

handle `revisions made` & `revisions requested disabled` application states

#96: request revisions data hookup

---

components/pages/Applications/ApplicationForm/Forms/Collaborators/index.tsx

Addresses some of the collaborator modal bugs.

214 - fix collaborator modal edit/add and student/staff labels

---

components/pages/Applications/ApplicationForm/Forms/Signature.tsx
components/pages/Applications/ApplicationForm/Header/index.tsx

- fix state not updating on submit (feedback from kim) - modal didn't have a reload action
- fix issue that justin found - when user's session expires, the header was crashing because data didn't have a default value

#288: state not updating in header

---

components/pages/Applications/ApplicationForm/Forms/Applicant.tsx
components/pages/Applications/ApplicationForm/Forms/Collaborators/index.tsx
components/pages/Applications/ApplicationForm/Forms/EthicsLetter/index.tsx
components/pages/Applications/ApplicationForm/Forms/ProjectInfo/index.tsx
components/pages/Applications/ApplicationForm/Forms/Representative.tsx
components/pages/Applications/ApplicationForm/Forms/Signature.tsx
components/pages/Applications/ApplicationForm/Forms/Terms.tsx
components/pages/Applications/ApplicationForm/Forms/index.tsx
components/pages/Applications/PDF/common.tsx

- added borders to UI section titles
- removed padding/borders on the sections themselves
- converted H3s to section titles

#196: fix borders on form

---

components/pages/Applications/ApplicationForm/Forms/validations/helpers.ts

add a space so react doesn't bug out about missing keys

#298: fix key issue in select element

---

components/pages/Applications/ApplicationForm/Forms/Collaborators/TableComponent.tsx
components/pages/Applications/ApplicationForm/Forms/Collaborators/index.tsx
components/pages/Applications/ApplicationForm/Forms/EthicsLetter/UploadsTable.tsx
components/pages/Applications/ApplicationForm/Forms/EthicsLetter/index.tsx
components/pages/Applications/ApplicationForm/Forms/validations/helpers.ts
components/pages/Applications/ApplicationForm/Forms/validations/index.ts
components/pages/Applications/ApplicationForm/Forms/validations/schemas.ts
package-lock.json
package.json

Tickets:
#54 (Feedback round)
#58
#214 (Feedback round)
#253
#298
#304

🔖 rc 0.21.1

---

package-lock.json
package.json

Get changes from https://github.com/icgc-argo/platform-ui/issues/2005

313 - update UiKit to fix word counter

---

components/pages/Applications/ApplicationForm/Forms/EthicsLetter/UploadsTable.tsx
components/pages/Applications/ApplicationForm/Forms/EthicsLetter/index.tsx
components/pages/Applications/PDF/StaticEthics.tsx
components/pages/Applications/PDF/textConstants.ts

241 - update Ethics copy

---

components/pages/Applications/PDF/StaticProjectInfo.tsx
components/pages/Applications/PDF/textConstants.ts

319 - update Project Info copy

---

components/pages/Applications/ApplicationForm/Forms/Appendices.tsx
components/pages/Applications/ApplicationForm/Forms/types.ts
components/pages/Applications/ApplicationForm/Forms/validations/schemas.ts
components/pages/Applications/PDF/StaticAppendices.tsx
components/pages/Applications/PDF/textConstants.ts
components/pages/Applications/types.ts
global/constants/externalPaths.ts

Updates appendix agreements related to [DAC-API-136](https://github.com/icgc-argo/dac-api/issues/136)
Updates types, links for these agreements

👽️ 330 - Update appendices for DAC-API-136 changes

---

components/pages/Applications/ApplicationForm/Forms/Outline/Section.tsx
components/pages/Applications/ApplicationForm/Forms/Outline/index.tsx
components/pages/Applications/ApplicationForm/Forms/index.tsx
components/pages/Applications/ApplicationForm/Forms/types.ts
components/pages/Applications/ApplicationForm/Forms/validations/helpers.ts
components/pages/Applications/ApplicationForm/Forms/validations/index.ts
components/pages/Applications/ApplicationForm/Forms/validations/schemas.ts
components/pages/Applications/ApplicationForm/index.tsx

Displays a section's overall status icon only after the user has modified any of its fields, and not before they move on to another section (i.e. not while filling up the section.)

191 - improve validation UX

---

components/pages/Applications/ApplicationForm/Forms/Applicant.tsx
components/pages/Applications/ApplicationForm/Forms/Collaborators/ErrorBanner.tsx
components/pages/Applications/ApplicationForm/Forms/Collaborators/index.tsx
components/pages/Applications/ApplicationForm/Forms/Outline/Section.tsx
components/pages/Applications/ApplicationForm/Forms/Outline/index.tsx
components/pages/Applications/ApplicationForm/Forms/index.tsx
components/pages/Applications/ApplicationForm/Forms/types.ts
components/pages/Applications/ApplicationForm/Forms/validations/helpers.ts
components/pages/Applications/ApplicationForm/Forms/validations/index.ts
components/pages/Applications/ApplicationForm/Forms/validations/schemas.ts
components/pages/Applications/ApplicationForm/index.tsx
components/pages/Applications/PDF/StaticApplicant.tsx
components/pages/Applications/PDF/StaticCollaborators.tsx
components/pages/Applications/PDF/StaticProjectInfo.tsx
components/pages/Applications/PDF/StaticRepresentative.tsx
global/hooks/useAuthContext.tsx
package.json

🔖 Rc/0.22.0

---

components/pages/Applications/ApplicationForm/Forms/Signature.tsx
components/pages/Applications/ApplicationForm/Forms/constants.tsx
components/pages/Applications/ApplicationForm/Forms/index.tsx
components/pages/Applications/ApplicationForm/Forms/validations/helpers.ts
components/pages/Applications/ApplicationForm/Forms/validations/index.ts
package-lock.json
package.json

Tickets included:
- #329
- #353
- #361
- #362
- #364

🔖 rc 0.23.1

---

components/pages/Applications/ManageApplications/index.tsx

changed too much on previous PR
just need sorting to be on appNumber not appId
this PR is to reset the default table sort back to status col

reset default sort for admin table

---

components/pages/Applications/ApplicationForm/Header/Details.tsx
components/pages/Applications/ApplicationForm/Header/index.tsx

Add expires at info to approved application details

add expires at detail for application

---

components/pages/Applications/ApplicationForm/RequestRevisionsBar/RejectModal.tsx
components/pages/Applications/ApplicationForm/RequestRevisionsBar/index.tsx

- add rejection modal (copy pasted from approval modal tbh)
- add button to open the modal

add reject modal

---

components/ApplicationProgressBar/index.tsx
components/pages/Applications/ApplicationForm/Forms/Collaborators/index.tsx
components/pages/Applications/ApplicationForm/Forms/index.tsx
components/pages/Applications/ApplicationForm/Header/Actions.tsx
components/pages/Applications/ApplicationForm/index.tsx

due to Prettier Ping Pong (TM @ciaranschutte) i added comments where i made changes

#415: application rejection state

---

components/pages/Applications/ApplicationForm/Forms/ProjectInfo/PublicationURLs.tsx

- get duplicates
- check if the given publication URL is a duplicate
- if so, show an error

#138: add validation for duplicate publication URLs

---

components/ApplicationProgressBar/index.tsx
components/pages/Applications/ApplicationForm/Forms/index.tsx
components/pages/Applications/ApplicationForm/Header/index.tsx
components/pages/Applications/Dashboard/Applications/InProgress/helpers.ts
components/pages/Applications/Dashboard/Applications/InProgress/index.tsx

- add request revisions flag to progress bar in the header in revision & submit states when revisions were requested
- only show submitted banner in review state
- in the dashboard card, make status text red & update copy

#299: add revisions requested flag

---

package-lock.json
package.json

#179: fix disabled colours

---

components/pages/Applications/ManageApplications/index.tsx
components/pages/Applications/types.ts
global/hooks/useDebounce.tsx
global/hooks/useGetApplications.tsx

Add search input to admin table.
Adds `useDebounce` from platform-ui to debounce search query, 300ms delay.

✨ 29 - table search

---

components/pages/Applications/ManageApplications/utils.tsx
components/pages/Applications/types.ts

Adds country column to admin table view.

✨ 418 - Add country to admin table

---

components/pages/Applications/ApplicationForm/Forms/index.tsx
components/pages/Applications/ApplicationForm/Header/Actions.tsx
components/pages/Applications/ApplicationForm/Header/index.tsx
components/pages/Applications/Dashboard/Applications/InProgress/ButtonGroup.tsx
components/pages/Applications/Dashboard/Applications/InProgress/index.tsx
global/config/index.tsx
global/constants/index.ts
next.config.js
pages/_app.tsx

Displays one-time notification when approved app is closed.
Displays permanent message on application progress card.
Small style change so button group on progress card maintains consistent alignment.
Adds daco survey url to config. Helm chart updated [here](https://github.com/OICR/argo-infra/pull/654)

✨ 463 - Add message, label for apps closed after approval

---

components/pages/Applications/ApplicationForm/Forms/ApplicationHistoryModal.tsx
components/pages/Applications/ApplicationForm/Forms/index.tsx
components/pages/Applications/ApplicationForm/Forms/types.ts

Data hookup for history modal. Removes feature flag, mock data. Displays generic error banner on data failure.

👽️ 471 - Data hookup for user app history modal

---

components/pages/Applications/ApplicationForm/Forms/Appendices.tsx
components/pages/Applications/ApplicationForm/Forms/Applicant.tsx
components/pages/Applications/ApplicationForm/Forms/Collaborators/index.tsx
components/pages/Applications/ApplicationForm/Forms/DataAccessAgreement.tsx
components/pages/Applications/ApplicationForm/Forms/EthicsLetter/index.tsx
components/pages/Applications/ApplicationForm/Forms/ProjectInfo/index.tsx
components/pages/Applications/ApplicationForm/Forms/Representative.tsx
components/pages/Applications/ApplicationForm/Forms/Signature.tsx
components/pages/Applications/ApplicationForm/Forms/Terms.tsx
components/pages/Applications/ApplicationForm/Forms/helpers.tsx
components/pages/Applications/ApplicationForm/Forms/index.tsx
components/pages/Applications/ApplicationForm/index.tsx
components/pages/Applications/PDF/StaticAppendices.tsx
components/pages/Applications/PDF/StaticApplicant.tsx
components/pages/Applications/PDF/StaticCollaborators.tsx
components/pages/Applications/PDF/StaticDataAccessAgreement.tsx
components/pages/Applications/PDF/StaticEthics.tsx
components/pages/Applications/PDF/StaticProjectInfo.tsx
components/pages/Applications/PDF/StaticRepresentative.tsx
components/pages/Applications/PDF/StaticTerms.tsx
components/pages/Applications/PDF/common.tsx
components/pages/Applications/PDF/types.ts
components/pages/Applications/types.ts

depends on changes from [dac-api-246](https://github.com/icgc-argo/dac-api/issues/246)
includes some minor type refactoring/fixes

✨ 495 - Add section lastUpdatedAt to form display

---

components/pages/Applications/ApplicationForm/Forms/ProjectInfo/index.tsx
components/pages/Applications/ApplicationForm/Forms/validations/schemas.ts
components/pages/Applications/PDF/StaticProjectInfo.tsx
components/pages/Applications/PDF/common.tsx
components/pages/Applications/PDF/textConstants.ts
global/constants/externalPaths.ts

Updates lay summary help text. Button link for guide will not show in PDF.
Adds placeholder link for lay summary guide.
Use constants for project info min/max words.

💄💬 488 - Update lay summary help text, min and max word validations

---

components/GdprBanner.tsx
components/Root.tsx
global/constants/index.ts

Adds same gdpr banner setup as in platform ui

💄 541 - Adds GDPR banner

---

components/NavBar.tsx
global/hooks/useAuthContext.tsx
global/utils/auth/logoutUtil.tsx
pages/_app.tsx

Reload the page after logout because the page wasn't updating after logout on develop.

#538 - reload page after logout

---

pages/_app.tsx

Display maintenance page when maintenance mode flag is on.
- `/new-website-notice` route will not display in this mode
- use flag `NEXT_PUBLIC_MAINTENANCE_MODE_ON` in helm

✨ 593 - Maintenance mode with feature flag

---

package.json

🔖 Rc/1.1.0

---

components/pages/Applications/PDF/StaticProjectInfo.tsx
package.json

Hotfix - daco folks requested pub urls be clickable in the pdf, and we wanted to avoid the attestation changes that have been merged into dev since the last release.

🚑️ 617 - make pub urls clickable in pdf

---

components/pages/Applications/ApplicationForm/Forms/index.tsx

For https://github.com/icgc-argo/dac-api/issues/341

👽️ change attestation req to boolean

---

components/pages/Applications/ApplicationForm/Header/Actions.tsx
components/pages/Applications/ApplicationForm/RequestRevisionsBar/index.tsx

Shows "Close Application" button in paused state
Shows PDF action buttons to admin in paused state

🩹 486 - correct action buttons for paused state

---

components/pages/Applications/ManageApplications/utils.tsx
components/pages/Applications/types.ts

Adds `type` column to admin table, showing if application is `New` or `Renewal`

✨ 515 - add type column to admin table

---

components/pages/Applications/Dashboard/Applications/InProgress/helpers.ts

Just clarifying the language for the status text on a pausing application

💬 status text update

---

package.json

🔖 Rc/1.7.1

---

components/pages/Applications/ApplicationForm/Forms/helpers.tsx
components/pages/Applications/ApplicationForm/Forms/index.tsx
components/pages/Applications/ApplicationForm/Header/Actions.tsx
components/pages/Applications/ApplicationForm/Header/index.tsx
components/pages/Applications/ApplicationForm/RequestRevisionsBar/index.tsx
components/pages/Applications/Dashboard/Applications/InProgress/ButtonGroup.tsx
components/pages/Applications/Dashboard/Applications/InProgress/index.tsx
global/utils/dates/helpers.ts

Logic fixes and cleanup for renewal banner display.
Minor fixes for dashboard status text, available admin actions and close app modal.

💄 666 - ux feedback

---

components/pages/Applications/PDF/common.tsx

More padding for project info static content, fixes text running outside border

💄 590 - More padding for project info list items

---

components/pages/Applications/ApplicationForm/Header/Actions.tsx

Adds extra confirm text input when closing an application to prevent accidental close.

✨ 665 - add confirm action when closing an app

---

components/pages/Applications/ApplicationForm/Header/Actions.tsx

Needs api change from https://github.com/icgc-argo/dac-api/pull/413

🐛 676 - paused app can download app package zip

---

components/pages/Applications/ApplicationForm/Forms/Collaborators/index.tsx

Disable collab modification in paused, expired states
API portion in https://github.com/icgc-argo/dac-api/pull/418

🐛 681 - disable collab edit/delete in paused, expired apps
