components/NavBar.tsx
global/constants/auth.ts
global/constants/index.ts
global/hooks/useAuthContext.tsx
global/utils/egoTokenUtils.tsx
package-lock.json
package.json
pages/_app.tsx
pages/logged-in.tsx

Applications nav tab label changes based on admin or applicant role
Includes update to ego-token-utils for daco admin role check (`8.2.0`)

💄 47 - Applications title based on user role

---

global/hooks/useHealthAPI.tsx

using axios directly for the health API endpoint because it's our only no-auth API request

footer API version: use axios instead of fetchWithAuth

---

components/Loader.tsx
components/pages/Applications/ApplicationForm/Header/index.tsx
components/pages/Applications/ApplicationForm/index.tsx
components/pages/Applications/types.ts
global/hooks/useApplicationsAPI.tsx
global/hooks/useAuthContext.tsx

using the Application header as a test subject, @samrichca pointed out the hook was missing the capacity to pass data body and methods other than GET. This PR addresses that, as well as covering some technical debt I had introduced in the header (which account for the extra changes).

add appId to useApplicationsApi

---

components/pages/Applications/ApplicationForm/Header/Actions.tsx
components/pages/Applications/Dashboard/Applications/InProgress/constants.ts
components/pages/Applications/PDF/Cover.tsx
components/pages/Applications/PDF/PdfLayout.tsx
components/pages/Applications/PDF/Signatures.tsx
components/pages/Applications/PDF/StaticApplicant.tsx
components/pages/Applications/PDF/StaticCollaborators.tsx
components/pages/Applications/PDF/StaticProjectInfo.tsx
components/pages/Applications/PDF/StaticRepresentative.tsx
components/pages/Applications/PDF/VerticalTable.tsx
components/pages/Applications/PDF/common.tsx
components/pages/Applications/PDF/types.ts
components/pages/Applications/types.ts
global/constants/externalPaths.ts

Adds Cover and Signatures page, these are for PDF only.
Fixes minute format in `TIME_AND_DATE_FORMAT`
Defaults VerticalTable to `wrap=false` to prevent weird double render of some rows
Makes VerticalTable header width customisable
VerticalTable values can now be strings or elements
Adds some missing typing
Fixes individual's display name to include `title` and `suffix`
Adds `projectInfo.summary` from api data

✨ 175 - cover signature pages

---

components/pages/Applications/PDF/StaticRepresentative.tsx
components/pages/Applications/types.ts

Representative address on pdf will use applicant address when `addressSameAsApplicant` is true

🐛 Rep address can use sameAsApplicant value

---

components/pages/Applications/ApplicationForm/Forms/helpers.tsx
components/pages/Applications/ApplicationForm/Forms/types.ts
components/pages/Applications/ApplicationForm/Forms/validations/index.ts

Couple of changes to the local state selector, to ensure the sections' individual states stop being sticky.
This was introduced when I tried to abstract this logic into a single place seeking to remove duplication (not all innovation is progress), but I didn't account for React being funny like this.

188 - fix local validation issue being sticky across sections

---

components/pages/Applications/ApplicationForm/Forms/Applicant.tsx
components/pages/Applications/ApplicationForm/Forms/Representative.tsx
components/pages/Applications/ApplicationForm/Forms/validations/index.ts

The select fields (e.g. Applicant and Representative `title`) are not saving changes on the first interaction, as the `blur` logic persists only data for fields that had been `touched` before the change.
This logic touches these upon focusing on them, so changes can be saved once the user moves away from them.

189 - add focus touch to select-one fields

---

components/pages/Applications/ApplicationForm/Forms/validations/index.ts

because `typeof null === 'object'`
┻━┻ ︵ヽ(`Д´)ﾉ︵ ┻━┻

add null check when updating local state

---

components/pages/Applications/ApplicationForm/Forms/Collaborators/TableComponent.tsx
components/pages/Applications/ApplicationForm/Forms/Collaborators/index.tsx
components/pages/Applications/ApplicationForm/Forms/types.ts
components/pages/Applications/ApplicationForm/Forms/validations/helpers.ts
components/pages/Applications/ApplicationForm/Forms/validations/index.ts
components/pages/Applications/ApplicationForm/Forms/validations/schemas.ts

An extra bit of useful complication for the validation monster.
Basically, when dealing with a `primaryAffiliation` field, compare it with the one in the applicant section, if available.
If the one in applicant changes, revalidate the others (representative and collaborators, currently).

54 - validate Primary Affiliation matches

---

components/pages/Applications/ApplicationForm/Forms/validations/index.ts

I had the wrong check for this trigger.
This change checks for any changes (even for `''`), rather than checking if there's a match.

54 - ensure applicant affiliation change triggers validation

---

components/pages/Applications/ApplicationForm/Forms/Collaborators/index.tsx
components/pages/Applications/ApplicationForm/Forms/validations/index.ts

adds logic to check all required fields in the modal have a value and ensure that the primary affiliation is valid, before enabling the magic button.
Bonus: fixes the `title` field

214 - enable add/edit collaborator button when modal is valid

---

components/pages/Applications/ApplicationForm/Forms/validations/helpers.ts

- changed the first option in select fields to 'select an option' with an empty string value
- empty string is the default for select fields (according to `schemas.ts`)

#298: add default blank option to select options

---

components/pages/Applications/ApplicationForm/Forms/validations/schemas.ts

Applies `trim` to the yup string schemas, to ensure validating inputs regardless of surrounding whitespace.
Bonus: shows error for required fields filled with blank space.
https://github.com/jquense/yup#stringtrimmessage-string--function-schema

304 - allow whitespace around text input before validation

---

components/pages/Applications/ApplicationForm/Forms/Collaborators/index.tsx
components/pages/Applications/ApplicationForm/Forms/validations/helpers.ts
components/pages/Applications/ApplicationForm/Forms/validations/index.ts

Moves the string trimming to the `on blur` stage of input from the save request preparation.
Also, ensures the cursor/prompt in input fields inside the modal windows stops jumping to the end of the field (like Ego-ui)

334 - ensure all text values are trimmed on input

---

components/pages/Applications/ApplicationForm/Forms/validations/index.ts

Fine tuning the validation notifications, we're supposed to show section status changes while the user fills up the form, as long as the status is not "incomplete" (aka error), which is only to be shown if the user moves onto a new section (or leaves the app) before fulfilling the sections' requirements.

346 - show SOME section status notifications

---

components/pages/Applications/PDF/StaticTerms.tsx

- Fixes the PDF styling to match the changes in the Terms section.
- Adds a new link, as per the ticket.
- Adds a missing period at the end of a paragraph.

345 - improve PDF Terms layout

---

components/pages/Applications/ApplicationForm/Forms/Applicant.tsx
components/pages/Applications/ApplicationForm/Forms/Representative.tsx
components/pages/Applications/ApplicationForm/Forms/validations/helpers.ts
components/pages/Applications/ApplicationForm/Forms/validations/index.ts
components/pages/Applications/ApplicationForm/Forms/validations/schemas.ts
package-lock.json
package.json

As per specification, the `multiselect` component now behaves more like a typeahead now (following the example set by HCMI).
Changes included in this PR (apart from updating the package version) include restoring the country field validations, and

93 - improve typeahead behaviour

---

components/pages/Applications/ApplicationForm/Forms/constants.tsx
components/pages/Applications/ApplicationForm/Forms/validations/helpers.ts
components/pages/Applications/ApplicationForm/Forms/validations/index.ts

Abstracts the comparison of fields with the Applicants' fields into a reusable helper, in case we have to add other checks anywhere.

329 - validate Applicant emails at collaborator modal

---

components/pages/Applications/ApplicationForm/Forms/Signature.tsx
components/pages/Applications/ApplicationForm/Forms/index.tsx
global/constants/index.ts
pages/_app.tsx

- add flash data, with reset on route change
- avoids adding more local state
- avoids ugly navigable urls eg. user navigates to `.../submissionSuccess=true`  with zero context

flash data successful submission banner

---

components/pages/Applications/ManageApplications/index.tsx
global/hooks/useGetApplications.tsx

Trim query value when sent to getApplications request, not in input value, so spaces can be used.
Send query param only when there's a value.

🐛 29 - Allow spaces in search query

---

components/pages/Applications/Dashboard/Applications/InProgress/helpers.ts
components/pages/Applications/Dashboard/Applications/InProgress/index.tsx
components/pages/Applications/types.ts

- applications in request revisions state already have red status text
- use the same text for applications in sign & submit state, if revisions were requested

#440: update status text for revisions requested

---

components/pages/Applications/Dashboard/Applications/InProgress/index.tsx
components/pages/Applications/ManageApplications/utils.tsx

Responsive alignment change for dashboard closed app badge.
Change admin table appId link to `router.push()` event to prevent shallow routing, allows use of path diffing for flash data reset

🐛 463 - Fix closed banner

---

components/pages/Applications/ApplicationForm/Header/Actions.tsx
components/pages/Applications/ManageApplications/index.tsx
global/utils/helpers.ts

Adds app history download on admin table.
Creates helper function for window downloads.
Depends on [dac-api 227](https://github.com/icgc-argo/dac-api/pull/271)

✨ 472 - Add app history download button

---

components/pages/Applications/ApplicationForm/Forms/ProjectInfo/PublicationURLs.tsx
components/pages/Applications/ApplicationForm/Forms/ProjectInfo/index.tsx
components/pages/Applications/ApplicationForm/Forms/helpers.tsx

Moves most publication error validation to backend; ui will display errors from api response
Empty field error remains with yup.
Notes on blank field error behaviour: 
- when a field is untouched, initial focus/blur event will create a blank field error, but on blur the form is submitted and the data is refreshed, and the item.error value is wiped from state.
- on a subsequent focus event, i.e. clicking the same empty field and blurring again, there is no data change so the form is NOT submitted and the item.error persists.
- once another field is modified, i.e. focussed, edited then blurred, the form is submitted and state is wiped again, erasing the empty field error on that previous field
- Due to the way the publications form is submitted, using api-side errors for blank fields …

🐛 439 - update pubs to use api side errors

---

components/Footer.tsx

@ciaranschutte did most of the work in [103](https://github.com/icgc-argo/dac-ui/issues/103) 😀 
This pr just hides the argo platform links in the footer

💄 539 - Hide platform links on maintenance page

---

components/pages/Applications/ApplicationForm/Forms/types.ts
components/pages/Applications/ApplicationForm/Forms/validations/helpers.ts
components/pages/Applications/ApplicationForm/Forms/validations/index.ts

Fixes bug where the required field error was not persisting on autocomplete fields when focusing/blurring with an empty value
- Adds a property `valueStayedEmpty` to prevent PATCH requests from firing when a field value remains an empty string after the blur event. `shouldPersistResults` was used for this check previously but caused unnecessary api requests on autocomplete fields
- Adds a comment about the different autofill behaviour of FF and Chrome

🐛 583 - Persist required field error on all text fields

---

Dockerfile
Jenkinsfile.groovy

latest node 16 version uses npm 8.11.0, which needs the `--legacy-peer-deps` to work with uikit

🐳  Fix npm ci command

---

components/pages/Applications/ApplicationForm/Header/Actions.tsx
components/pages/Applications/ApplicationForm/Header/Details.tsx
components/pages/Applications/ApplicationForm/Header/index.tsx
components/pages/Applications/types.ts

Minor fixes/refactoring for `PAUSED` app ui
- fixes typo
- adds `PAUSED` app case for PDF button text
- refactors access info comp to account for other conditions besides expiry
- moaarr types
- uses `isAttestable` value from api instead of doing any assessment from ui side

♻️✏️ 484 - Refactoring for app access info, typo fix

---

components/pages/Applications/ApplicationForm/Forms/index.tsx
components/pages/Applications/ApplicationForm/Header/index.tsx
components/pages/Applications/Dashboard/Applications/InProgress/helpers.ts
components/pages/Applications/Dashboard/Applications/InProgress/index.tsx
components/pages/Applications/Dashboard/Applications/index.tsx
components/pages/Applications/ManageApplications/utils.tsx
components/pages/Applications/types.ts

Use `lastPausedAtUtc` value from api instead of calculating from updates array and `attestationByUtc`
- `attestationByUtc` will still be a fallback value, but if an application is in `PAUSED` state there should be at least one paused event in the updates list
- uses changes from https://github.com/icgc-argo/dac-api/pull/343
- Also some type renaming to align more with api types because it wasn't clear to me what `ApplicationsResponseItem` was 🙂

👽️ 630 - correct pause date

---

components/pages/Applications/Dashboard/Applications/InProgress/ButtonGroup.tsx
components/pages/Applications/Dashboard/Applications/InProgress/helpers.ts
components/pages/Applications/Dashboard/Applications/InProgress/index.tsx
components/pages/Applications/types.ts
global/constants/internalPaths.ts

Dashboard status text, date and renew button for approved applications within the renewal period (before expiry).
Refactors some of the conditionals for status display.
Allows a custom Button component
Adds calc function for renewal period end date (expiry + 90 days) - currently this is hardcoded, either switch to a configurable value, or get this value from the BE in some form (a new field or retrieve config from api)

✨ 504 - Add expiring status, renew button to dashboard card

---

components/pages/Applications/Dashboard/Applications/InProgress/ButtonGroup.tsx
components/pages/Applications/Dashboard/Applications/InProgress/helpers.ts
components/pages/Applications/Dashboard/Applications/InProgress/index.tsx
global/utils/dates/helpers.ts

Styles, text content and buttons for EXPIRED app dashboard cards, including expired while still in renewal period and expired after renewal period ends
- also creates dates util folder for date-specific custom functions. Will move existing constants/helper functions to this folder in a separate PR!

✨ 505 - add status text and date for expired dashboard apps

---

components/pages/Applications/ApplicationForm/Forms/ApplicationHistoryModal.tsx
components/pages/Applications/ApplicationForm/Forms/types.ts

Display `SYSTEM` role in application history modal as `DACO System` for clarity.
- add `SYSTEM` DacoRole enum

💬 653 - Add System DacoRole, app history display text

---

components/pages/Applications/ApplicationForm/Forms/ApplicationHistoryModal.tsx
components/pages/Applications/ApplicationForm/Forms/EthicsLetter/UploadsTable.tsx
components/pages/Applications/ApplicationForm/Forms/Signature.tsx
components/pages/Applications/ApplicationForm/Forms/common.tsx
components/pages/Applications/ApplicationForm/Forms/index.tsx
components/pages/Applications/ApplicationForm/Header/Details.tsx
components/pages/Applications/ApplicationForm/Header/index.tsx
components/pages/Applications/ApplicationForm/RequestRevisionsBar/ApproveModal.tsx
components/pages/Applications/ApplicationForm/RequestRevisionsBar/PDFActions.tsx
components/pages/Applications/Dashboard/Applications/CollaboratorApplication/index.tsx
components/pages/Applications/Dashboard/Applications/InProgress/helpers.ts
components/pages/Applications/Dashboard/Applications/InProgress/index.tsx
components/pages/Applications/ManageApplications/utils.tsx
components/pages/Applications/PDF/Cover.tsx
components/pages/Applications/PDF/common.tsx
components/pages/Applications/types.ts
global/constants/index.ts
global/utils/dates/constants.ts
global/utils/dates/helpers.ts
global/utils/dates/types.ts

Reorganize date format constants into enums, add to global/dates folder.
Move `getFormattedDate` helper func to global/dates folder. Add error clause.
Replace most `date-fns/format` calls with helper func.
**Does not modify/remove DateFormat string options, should discuss whether any of these can be pruned first.**

♻️ Refactor date formatters

---

components/pages/Applications/Dashboard/Applications/InProgress/helpers.ts
components/pages/Applications/Dashboard/Applications/InProgress/index.tsx
components/pages/Applications/types.ts

Adds custom text/status for renewal cards in `DRAFT`, `SIGN AND SUBMIT` or `REVISIONS REQUESTED`
Adds status date as well, but need to decide what the display text should be.

💄 506 - renewal app card

---

components/pages/Applications/ManageApplications/utils.tsx

Move type column after app status column in admin table view so status shows without need for horizontal scroll.

💄 515 - admin table - move type column after app status column

---

components/pages/Applications/ApplicationForm/RequestRevisionsBar/ApplicationActions.tsx
components/pages/Applications/ApplicationForm/RequestRevisionsBar/index.tsx

Disable "Revisions Requested" button when renewal period has ended (90 days after the source app has expired).
- the close unsubmitted renewals job does not close applications past their renewal period if they are in `REVIEW` state, but we do not allow more changes beyond this point

💄 638 - disable revisions when renewal period is ended
